name: Auto-merge
on: pull_request

permissions:
  pull-requests: write
  contents: write
  repository-projects: read

jobs:
  check-branch-protection:
    runs-on: ubuntu-latest
    outputs:
      protection-enabled: ${{ steps.check-protection.outputs.protection-enabled }}
      required-approvals: ${{ steps.check-protection.outputs.required-approvals }}
    steps:
      - name: Check branch protection rules
        id: check-protection
        run: |
          PROTECTION_API_PATH="/repos/${{ github.repository }}/branches/${{ github.event.pull_request.base.ref }}/protection"

          PROTECTION_RULES=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${PROTECTION_API_PATH}" \
            2>/dev/null || true)
          echo "::notice::Protection rules response: ${PROTECTION_RULES}"

          if [ -z "$PROTECTION_RULES" ]; then
            echo "::warning::Branch protection is not enabled for ${{ github.event.pull_request.base.ref }}"
            echo "protection-enabled=false" >> "$GITHUB_OUTPUT"
            echo "required-approvals=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          REQUIRED_APPROVALS=$(echo "$PROTECTION_RULES" | jq -r '.required_pull_request_reviews.required_approving_review_count // 0')
          echo "protection-enabled=true" >> "$GITHUB_OUTPUT"
          echo "required-approvals=${REQUIRED_APPROVALS}" >> "$GITHUB_OUTPUT"

          if [ "$REQUIRED_APPROVALS" -eq 0 ]; then
            echo "::warning::Branch ${{ github.event.pull_request.base.ref }} does not require approving reviews"
          else
            echo "::notice::Branch protection verified: ${{ github.event.pull_request.base.ref }} requires ${REQUIRED_APPROVALS} approval(s)"
          fi
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  dependabot:
    runs-on: ubuntu-latest
    needs: check-branch-protection
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      needs.check-branch-protection.outputs.protection-enabled == 'true' &&
      needs.check-branch-protection.outputs.required-approvals > 0
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          echo "Branch protection confirmed: requires ${{ needs.check-branch-protection.outputs.required-approvals }} approval(s)"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
