name: Build
on:
  pull_request:
  push:
jobs:
  run_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: npm ci
      - name: Build applications
        env:
          DISABLE_ESLINT_PLUGIN: true
        run: npm run build
